name: Initialize Marketplace Action Request

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  parse-issue:
    runs-on: self-hosted
    outputs:
      payload: ${{ steps.issue_parser.outputs.json }}
    steps:
      - name: Check out request parser and validator
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Parse issue form
        id: issue_parser
        uses: issue-ops/parser@cb7e2e4e5da701aad0e23e718bc4c91d442ca8ba # v5.0.0
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: request_marketplace_action.yml
      - name: Validate requested repository
        if: steps.issue_parser.outputs.parsed_owner != '' && steps.issue_parser.outputs.parsed_repo != '' && steps.issue_parser.outputs.parsed_version != ''
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          REQUEST_PAYLOAD: ${{ steps.issue_parser.outputs.json }}
        with:
          script: |
            const { default: validateRequest } = await import('${{ github.workspace }}/.github/scripts/validate-request.mjs');
            validateRequest(process.env.REQUEST_PAYLOAD);
  initialize-request:
    runs-on: self-hosted
    needs: parse-issue
    if: fromJson(needs.parse-issue.outputs.payload).owner != '' && fromJson(needs.parse-issue.outputs.payload).repo != '' && fromJson(needs.parse-issue.outputs.payload).version != ''
    steps:
    - name: Lookup the latest release of ${{ fromJson(needs.parse-issue.outputs.payload).owner }}/${{ fromJson(needs.parse-issue.outputs.payload).repo }}
      id: get_version
      env:
        OWNER: ${{ fromJson(needs.parse-issue.outputs.payload).owner }}
        REPO: ${{ fromJson(needs.parse-issue.outputs.payload).repo }}
        REQUEST_VERSION: ${{ fromJson(needs.parse-issue.outputs.payload).version }}
      run: |
        if [ "$REQUEST_VERSION" = 'latest' ]; then
          echo "Finding latest release of $OWNER/$REPO..."
          VERSION=$(curl "https://api.github.com/repos/$OWNER/$REPO/releases/latest" | jq -r .name)
          if [ "$VERSION" == "null" ]; then
            echo "No latest version found for $OWNER/$REPO"
            exit 1
          fi
        else
          VERSION="$REQUEST_VERSION"
        fi
        echo "VERSION: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
    - name: Check out scripts
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '24'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    - name: Create the repo ${{ fromJson(needs.parse-issue.outputs.payload).repo }}_${{ steps.get_version.outputs.version }} on GitHub Enterprise Server
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        VERSION: ${{ steps.get_version.outputs.version }}
        OWNER: ${{ fromJson(needs.parse-issue.outputs.payload).owner }}
        REPO: ${{ fromJson(needs.parse-issue.outputs.payload).repo }}
      with:
        debug: true
        script: |
          const { default: initialize } = await import('${{ github.workspace }}/.github/scripts/initialize-request.mjs');
          const options = { 
            token: '${{ secrets.TOKEN }}',
            actionsApprovedOrg: '${{ vars.ACTIONS_APPROVED_ORG }}',
            baseUrl: '${{ github.api_url }}',
            version: process.env.VERSION,
            owner: process.env.OWNER,
            repo: process.env.REPO
          };
          await initialize(github, context, options);
    - name: Check out requested action repo ${{ fromJson(needs.parse-issue.outputs.payload).owner }}/${{ fromJson(needs.parse-issue.outputs.payload).repo }}_${{ steps.get_version.outputs.version }}
      env:
        OWNER: ${{ fromJson(needs.parse-issue.outputs.payload).owner }}
        REPO: ${{ fromJson(needs.parse-issue.outputs.payload).repo }}
      run: |
        git clone "https://github.com/$OWNER/$REPO" requested-action
    - name: Push requested action to private repo in $ACTIONS_APPROVED_ORG org on GitHub Enterprise Server
      env:
        REPO: ${{ fromJson(needs.parse-issue.outputs.payload).repo }}
        VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        cd requested-action
        git config user.email '${{ secrets.GITHUB_EMAIL }}'
        git config user.name '${{ secrets.GITHUB_USERNAME }}'
        if git checkout main; then
          git branch -m main-old
        fi
        git checkout "$VERSION"
        git switch -c "$VERSION"-branch
        git branch -m main
        export GHHOST=${{ github.server_url }}
        git remote add origin2 https://${{ secrets.TOKEN }}@${GHHOST#https://}/${{ vars.ACTIONS_APPROVED_ORG }}/"$REPO"_"$VERSION".git
        git push -u origin2 main
        git push -u origin2 "$VERSION"
        